spring:
  application:
    name: market-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
  datasource:
    url: jdbc:postgresql://localhost:5432/market_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate