spring:
  application:
    name: comm-service
#  config:
#    import: "configserver:http://config-service"
#  profiles:
#    active: ${profile:prod}


s3:
  bucket:
    commImg: "sesac-bytogether-bucket"
