spring:
  config:
    import: "configserver:http://config-server:8888"
  application:
    name: comm-service
  profiles:
    active: ${profile:docker}


s3:
  bucket:
    commImg: "sesac-bytogether-bucket"
