spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888"
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MASTER_MAIL_ACCOUNT}
    password: ${MASTER_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    #Kakao Oauth2 ??
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: { KAKAO_CLIENT_ID }
#            client-secret: { KAKAO_CLIENT_SECRET }
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - profile_nickname
#              - account_email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: { USER_ID }