spring:
  application:
    name: chat-service
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:prod}
#  config:
#    import: ${SPRING_CONFIG_IMPORT:configserver:http://config-service}
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
